validator.class: SeqGenerationValidator
validator.params:
  eval_dataset: parallel_text
  eval_dataset.params:
    src_file: ./data/dev/dev.src
    trg_file: ./data/dev/dev.trg
  eval_batch_size: 64
  eval_start_at: 0
  eval_steps: 1000
  eval_criterion: label_smoothed_cross_entropy
  eval_search_method: beam_search
  eval_search_method.params:
    beam_size: 4
    length_penalty: 0.6
    extra_decode_length: 50
    maximum_decode_length: 120
  eval_metric: tok_bleu
  eval_top_checkpoints_to_keep: 10
  eval_auto_average_checkpoints: true
  